export const Mock = [
  {
    id: '1',
    name: 'Standard',
    artToBeColored: '200',
    numOfArt: '200',
    amount: '10',
    amountOfHint: '10',
  },
  {
    id: '2',
    name: 'Medium',
    artToBeColored: '200',
    numOfArt: '200',
    amount: '10',
    amountOfHint: '10',
  },
  {
    id: '3',
    name: 'Pro',
    artToBeColored: '200',
    numOfArt: '200',
    amount: '10',
    amountOfHint: '10',
  },
  {
    id: '1',
    name: 'Standard',
    artToBeColored: '200',
    numOfArt: '200',
    amount: '10',
    amountOfHint: '10',
  },
  {
    id: '2',
    name: 'Medium',
    artToBeColored: '200',
    numOfArt: '200',
    amount: '10',
    amountOfHint: '10',
  },
  {
    id: '3',
    name: 'Pro',
    artToBeColored: '200',
    numOfArt: '200',
    amount: '10',
    amountOfHint: '10',
  },
];
